[package]
edition = "2018"
name = "online-profile-runtime-api"
version = "0.1.0"

[dependencies]
codec = { package = "parity-scale-codec", version = "2.0.0", default-features = false, features = [
  "derive",
] }
online-profile = { version = "0.1.0", path = "../../../online-profile", default-features = false }

[dependencies.sp-api]
default-features = false
git = 'https://github.com/paritytech/substrate.git'
rev = '49a4103f4bfef55be20a5c6d26e18ff3003c3353'
version = '3.0.0'

[dependencies.sp-runtime]
default-features = false
git = 'https://github.com/paritytech/substrate.git'
rev = '49a4103f4bfef55be20a5c6d26e18ff3003c3353'
version = '3.0.0'

[dependencies.sp-std]
default-features = false
git = 'https://github.com/paritytech/substrate.git'
rev = '49a4103f4bfef55be20a5c6d26e18ff3003c3353'
version = '3.0.0'

[dependencies.dbc-support]
default-features = false
package = 'dbc-support'
path = '../../../support'

[features]
default = ["std"]
std = [
  "codec/std",
  "online-profile/std",
  "sp-api/std",
  "sp-runtime/std",
  "sp-std/std",
  "dbc-support/std",
]
