[workspace]
members = [
    'bench',
    'browser-testing',
    'cli',
    'executor',
    'inspect',
    'primitives',
    'rpc',
    'rpc-client',
    'runtime',
    'testing',
    'pallets/dbc-staking',
    'pallets/random-num',
    'pallets/dbc-testing',
    'pallets/dbc-price-ocw',
    'pallets/online-profile',
    'pallets/online-profile-ocw',
    'pallets/lease-committee',
    'pallets/maintain-committee',
    'traits/phase-reward',
    'traits/online-profile-machine',
]
[profile.release]
panic = 'unwind'
