[workspace]
members = [
    'bench',
    'browser-testing',
    'cli',
    'executor',
    'inspect',
    'primitives',
    'rpc',
    'rpc-client',
    'runtime',
    'testing',
    'pallets/dbc-staking',
    'pallets/dbc-testing',
    'traits/phase-reward',
    'pallets/dbc-price',
    'pallets/online-profile',
]
[profile.release]
panic = 'unwind'
