[workspace]
members = [
    'bench',
    'browser-testing',
    'cli',
    'executor',
    'inspect',
    'primitives',
    'rpc',
    'rpc-client',
    'runtime',
    'testing',
    'pallets/*', 
    'traits/*', 
]
[profile.release]
panic = 'unwind'
