[workspace]
members = [
    'bench',
    'browser-testing',
    'cli',
    'executor',
    'inspect',
    'primitives',
    'rpc',
    'rpc-client',
    'runtime',
    'testing',
    'pallets/dbc-staking',
    'pallets/generic-func',
    'pallets/dbc-testing',
    'pallets/dbc-price-ocw',
    'pallets/online-profile',
    'pallets/online-profile/rpc',
    'pallets/online-profile/rpc/runtime-api',
    'pallets/committee',
    'pallets/lease-committee',
    'pallets/lease-committee/rpc',
    'pallets/lease-committee/rpc/runtime-api',
    'pallets/simple-rpc',
    'pallets/simple-rpc/rpc',
    'pallets/simple-rpc/rpc/runtime-api',
    'pallets/maintain-committee',
    'traits/phase-reward',
    'traits/online-profile-machine',
    'pallets/rent-machine',
    'pallets/rent-machine/rpc',
    'pallets/rent-machine/rpc/runtime-api',
]
[profile.release]
panic = 'unwind'
