[[bin]]
name = "polkadot"
path = "src/main.rs"

[package]
name = "dbc"
version = "3.0.0"

[dependencies]
cli = { package = "dbc-cli", path = "cli" }

[workspace]
members = [
  "bench",
  "cli",
  "executor",
  "inspect",
  "primitives",
  "rpc",
  "runtime",
  "testing"
]
