[package]
authors = ["bobo <dongkaige@gmail.com>"]
edition = "2018"
name = "online-profile"
version = "0.1.0"

[dependencies]
bs58 = { package = "bs58", version = "0.4.0", default-features = false }
codec = { package = "parity-scale-codec", version = "2.0.0", default-features = false, features = [
  "derive",
] }
serde = { version = "1.0.101", optional = true, features = ["derive"] }

frame-support = { git = 'https://github.com/paritytech/substrate', tag = 'v3.0.0', default-features = false }
frame-system = { git = 'https://github.com/paritytech/substrate', tag = 'v3.0.0', default-features = false }
sp-std = { git = 'https://github.com/paritytech/substrate', tag = 'v3.0.0', default-features = false }
sp-runtime = { git = 'https://github.com/paritytech/substrate', tag = 'v3.0.0', default-features = false }
sp-io = { git = 'https://github.com/paritytech/substrate', tag = 'v3.0.0', default-features = false }
sp-core = { git = 'https://github.com/paritytech/substrate', tag = 'v3.0.0', default-features = false }

dbc-support = { path = "../support", default-features = false }
generic-func = { path = '../generic-func', default-features = false }
dbc-price-ocw = { path = '../dbc-price-ocw', default-features = false }

[dev-dependencies]
sp-keyring = { git = 'https://github.com/paritytech/substrate', tag = 'v3.0.0' }
sp-core = { git = 'https://github.com/paritytech/substrate', tag = 'v3.0.0' }
pallet-balances = { git = 'https://github.com/paritytech/substrate', tag = 'v3.0.0' }
sp-io = { git = 'https://github.com/paritytech/substrate', tag = 'v3.0.0' }
pallet-randomness-collective-flip = { git = 'https://github.com/paritytech/substrate', tag = 'v3.0.0' }

pallet-staking = { package = 'dbc-staking', path = '../dbc-staking' }

[features]
default = ["std"]
std = [
  "codec/std",
  "dbc-price-ocw/std",
  "frame-support/std",
  "frame-system/std",
  "generic-func/std",
  "dbc-support/std",
  "sp-core/std",
  "sp-io/std",
  "sp-std/std",
  "sp-runtime/std",
  "serde",
]
