[package]
name = "terminating-rental-runtime-api"
version = "0.1.0"
edition = "2018"

[dependencies]
codec = { package = "parity-scale-codec", version = "2.0.0", default-features = false, features = ["derive"] }
terminating-rental = { version = "0.1.0", path = "../../../terminating-rental", default-features = false }

sp-api = { git = 'https://github.com/paritytech/substrate', rev = '49a4103f4bfef55be20a5c6d26e18ff3003c3353', default-features = false }
sp-runtime = { git = 'https://github.com/paritytech/substrate', rev = '49a4103f4bfef55be20a5c6d26e18ff3003c3353', default-features = false }
sp-std = { git = 'https://github.com/paritytech/substrate', rev = '49a4103f4bfef55be20a5c6d26e18ff3003c3353', default-features = false }

dbc-support = { path = '../../../support', default-features = false }

[features]
default = ["std"]
std = [
  "codec/std",
  "terminating-rental/std",
  "sp-api/std",
  "sp-runtime/std",
  "sp-std/std",
  "dbc-support/std",
]
