[package]
authors = ["bobo <dongkaige@gmail.com>"]
edition = "2018"
name = "committee-runtime-api"
version = "0.1.0"

[dependencies]
codec = { package = "parity-scale-codec", version = "2.0.0", default-features = false, features = ["derive"] }
committee = { version = "0.1.0", path = "../../../committee", default-features = false }
sp-api = { git = 'https://github.com/paritytech/substrate', tag = 'v3.0.0', default-features = false }
sp-runtime = { git = 'https://github.com/paritytech/substrate', tag = 'v3.0.0', default-features = false }
sp-std = { git = 'https://github.com/paritytech/substrate', tag = 'v3.0.0', default-features = false }

[features]
default = ["std"]
std = [
  "codec/std",
  "committee/std",
  "sp-api/std",
  "sp-runtime/std",
  "sp-std/std",
]
