[package]
authors = ["bobo <dongkaige@gmail.com>"]
edition = "2018"
name = "simple-rpc-runtime-api"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
codec = { package = "parity-scale-codec", version = "2.0.0", default-features = false, features = ["derive"] }
simple-rpc = { version = "0.1.0", path = "../../../simple-rpc", default-features = false }

sp-api = { git = 'https://github.com/paritytech/substrate', rev = '49a4103f4bfef55be20a5c6d26e18ff3003c3353', default-features = false }
sp-std = { git = 'https://github.com/paritytech/substrate', rev = '49a4103f4bfef55be20a5c6d26e18ff3003c3353', default-features = false }

[features]
default = ["std"]
std = ["sp-api/std", "sp-std/std"]
