[package]
name = "online-profile-rpc"
version = "0.1.0"
edition = "2018"

[dependencies]
codec = { package = "parity-scale-codec", version = "2.0.0", default-features = false, features = ["derive"] }
# serde = { version = "1.0.101", features = ["derive"], optional = true } # TODO: 是否移除features
serde = { version = "1.0.101", features = ["derive"]} # TODO: 是否移除features
jsonrpc-core = "15.0"
jsonrpc-core-client = "15.0"
jsonrpc-derive = "15.0"

online-profile = { version = "0.1.0", path = "../../online-profile", default-features = false }

# local packages

online-profile-runtime-api = { version = "0.1.0", path = "./runtime-api", default-features = false }

[dependencies.sp-api]
default-features = false
git = 'https://github.com/paritytech/substrate.git'
rev = '49a4103f4bfef55be20a5c6d26e18ff3003c3353'
version = '3.0.0'

[dependencies.sp-runtime]
default-features = false
git = 'https://github.com/paritytech/substrate.git'
rev = '49a4103f4bfef55be20a5c6d26e18ff3003c3353'
version = '3.0.0'

[dependencies.sp-blockchain]
default-features = false
git = 'https://github.com/paritytech/substrate.git'
rev = '49a4103f4bfef55be20a5c6d26e18ff3003c3353'
version = '3.0.0'

[dependencies.sp-rpc]
default-features = false
git = 'https://github.com/paritytech/substrate.git'
rev = '49a4103f4bfef55be20a5c6d26e18ff3003c3353'
version = '3.0.0'

[features]
default = ["std"]
std = [
    "sp-api/std",
    "sp-runtime/std",
    "online-profile-runtime-api/std",
    "online-profile/std",
]
