[package]
edition = "2018"
name = "online-profile-rpc"
version = "0.1.0"

[dependencies]
codec = { package = "parity-scale-codec", version = "2.0.0", features = ["derive"] }
jsonrpc-core = "15.0"
jsonrpc-core-client = "15.0"
jsonrpc-derive = "15.0"
serde = { version = "1.0.101", features = ["derive"] }
generic-func = { version = "0.1.0", path = "../../generic-func" }
dbc-support = { version = "0.1.0", path = "../../support" }
online-profile = { version = "0.1.0", path = "../../online-profile" }
online-profile-runtime-api = { version = "0.1.0", path = "./runtime-api" }

sp-api = { git = "https://github.com/paritytech/substrate", tag = "v3.0.0" }
sp-runtime = { git = "https://github.com/paritytech/substrate", tag = "v3.0.0" }
sp-blockchain = { git = "https://github.com/paritytech/substrate", tag = "v3.0.0" }
sp-rpc = { git = "https://github.com/paritytech/substrate", tag = "v3.0.0" }
