[package]
edition = "2018"
name = "online-committee-rpc"
version = "0.1.0"

[dependencies]
codec = { package = "parity-scale-codec", version = "2.0.0", features = ["derive"] }
jsonrpc-core = "15.0"
jsonrpc-core-client = "15.0"
jsonrpc-derive = "15.0"
serde = { version = "1.0.101", features = ["derive"] }
dbc-support = { version = "0.1.0", path = "../../support" }
online-committee = { version = "0.1.0", path = "../../online-committee" }
online-committee-runtime-api = { version = "0.1.0", path = "./runtime-api" }

sp-api = { git = 'https://github.com/paritytech/substrate', rev = '49a4103f4bfef55be20a5c6d26e18ff3003c3353' }
sp-runtime = { git = 'https://github.com/paritytech/substrate', rev = '49a4103f4bfef55be20a5c6d26e18ff3003c3353' }
sp-blockchain = { git = 'https://github.com/paritytech/substrate', rev = '49a4103f4bfef55be20a5c6d26e18ff3003c3353' }
sp-rpc = { git = 'https://github.com/paritytech/substrate', rev = '49a4103f4bfef55be20a5c6d26e18ff3003c3353' }
