[package]
authors = ["bobo <dongkaige@gmail.com>"]
edition = "2018"
name = "simple-rpc"
version = "0.1.0"

[dependencies]
codec = { package = "parity-scale-codec", version = "2.0.0", default-features = false, features = [
  "derive"
] }
dbc-support = { package = "dbc-support", path = "../support", default-features = false }
serde = { version = "1.0.101", optional = true, features = ["derive"] }

[dependencies.generic-func]
default-features = false
package = 'generic-func'
path = '../generic-func'

[dependencies.online-profile]
default-features = false
package = 'online-profile'
path = '../online-profile'

[dependencies.pallet-identity]
default-features = false
git = 'https://github.com/paritytech/substrate.git'
rev = '49a4103f4bfef55be20a5c6d26e18ff3003c3353'
version = '3.0.0'

[dependencies.frame-system]
default-features = false
git = 'https://github.com/paritytech/substrate.git'
rev = '49a4103f4bfef55be20a5c6d26e18ff3003c3353'
version = '3.0.0'

[dependencies.frame-support]
default-features = false
git = 'https://github.com/paritytech/substrate.git'
rev = '49a4103f4bfef55be20a5c6d26e18ff3003c3353'
version = '3.0.0'

[dependencies.sp-std]
default-features = false
git = 'https://github.com/paritytech/substrate.git'
rev = '49a4103f4bfef55be20a5c6d26e18ff3003c3353'
version = '3.0.0'

[features]
default = ["std"]
std = [
  "pallet-identity/std",
  "frame-system/std",
  "frame-support/std",
  "serde",
  "sp-std/std",
  "generic-func/std",
]
