[package]
authors = ["bobo <dongkaige@gmail.com>"]
edition = "2018"
name = "online-committee"
version = "0.1.0"

[dependencies]
codec = { package = "parity-scale-codec", version = "2.0.0", default-features = false, features = ["derive"] }
dbc-support = { path = "../support", default-features = false }
serde = { version = "1.0.101", optional = true, features = ["derive"] }

frame-support = { git = 'https://github.com/paritytech/substrate', tag = 'v3.0.0', default-features = false }
frame-system = { git = 'https://github.com/paritytech/substrate', tag = 'v3.0.0', default-features = false }
sp-std = { git = 'https://github.com/paritytech/substrate', tag = 'v3.0.0', default-features = false }
sp-runtime = { git = 'https://github.com/paritytech/substrate', tag = 'v3.0.0', default-features = false }
sp-io = { git = 'https://github.com/paritytech/substrate', tag = 'v3.0.0', default-features = false }

online-profile = { path = '../online-profile', default-features = false }
generic-func = { path = '../generic-func', default-features = false }
committee = { path = '../committee', default-features = false }

[dev-dependencies]
once_cell = '1'
hex = '0.4'

sp-core = { git = 'https://github.com/paritytech/substrate', tag = 'v3.0.0' }
sp-io = { git = 'https://github.com/paritytech/substrate', tag = 'v3.0.0' }
pallet-balances = { git = 'https://github.com/paritytech/substrate', tag = 'v3.0.0' }
pallet-randomness-collective-flip = { git = 'https://github.com/paritytech/substrate', tag = 'v3.0.0' }
sp-keyring = { git = 'https://github.com/paritytech/substrate', tag = 'v3.0.0' }
pallet-treasury = { git = 'https://github.com/paritytech/substrate', tag = 'v3.0.0' }
pallet-identity = { git = 'https://github.com/paritytech/substrate', tag = 'v3.0.0' }
pallet-collective = { git = 'https://github.com/paritytech/substrate', tag = 'v3.0.0' }
pallet-timestamp = { git = 'https://github.com/paritytech/substrate', tag = 'v3.0.0' }

dbc-price-ocw = { path = '../dbc-price-ocw' }

[features]
default = ["std"]
std = [
  "codec/std",
  "committee/std",
  "frame-support/std",
  "frame-system/std",
  "online-profile/std",
  "generic-func/std",
  "serde",
  "sp-io/std",
  "sp-runtime/std",
  "sp-std/std",
  "dbc-support/std",
]
