[package]
name = "rent-machine"
version = "0.1.0"
edition = "2018"

[dependencies]
codec = { package = "parity-scale-codec", version = "2.0.0", default-features = false, features = ["derive"] }
serde = { version = "1.0.101", optional = true }
serde_json = { version = "1", default-features = false, git = "https://github.com/kaigedong/json", branch = "no-std", features = ["alloc"] }

[dependencies.frame-support]
default-features = false
git = 'https://github.com/paritytech/substrate.git'
rev = '49a4103f4bfef55be20a5c6d26e18ff3003c3353'
version = '3.0.0'

[dependencies.frame-system]
default-features = false
git = 'https://github.com/paritytech/substrate.git'
rev = '49a4103f4bfef55be20a5c6d26e18ff3003c3353'
version = '3.0.0'

[dependencies.sp-std]
default-features = false
git = 'https://github.com/paritytech/substrate.git'
rev = '49a4103f4bfef55be20a5c6d26e18ff3003c3353'
version = '3.0.0'

[dependencies.sp-runtime]
default-features = false
git = 'https://github.com/paritytech/substrate.git'
rev = '49a4103f4bfef55be20a5c6d26e18ff3003c3353'
version = '3.0.0'

[dependencies.sp-io]
default-features = false
git = 'https://github.com/paritytech/substrate.git'
rev = '49a4103f4bfef55be20a5c6d26e18ff3003c3353'
version = '3.0.0'

[dependencies.online-profile]
default-features = false
path = '../online-profile'
package = 'online-profile'

[dependencies.dbc-price-ocw]
default-features = false
path = '../dbc-price-ocw'
package = 'dbc-price-ocw'

[features]
default = ["std"]
std = [
    "codec/std",
    "dbc-price-ocw/std",
    "frame-support/std",
    "frame-system/std",
    "online-profile/std",
    "serde",
    "sp-io/std",
    "sp-runtime/std",
    "sp-std/std",
]
