[package]
edition = "2018"
name = "rent-machine"
version = "0.1.0"

[dependencies]
codec = { package = "parity-scale-codec", version = "2.0.0", default-features = false, features = ["derive"] }
dbc-support = { path = "../support", default-features = false }
serde = { version = "1.0.101", optional = true }

frame-support = { git = 'https://github.com/paritytech/substrate', rev = '49a4103f4bfef55be20a5c6d26e18ff3003c3353', default-features = false }
frame-system = { git = 'https://github.com/paritytech/substrate', rev = '49a4103f4bfef55be20a5c6d26e18ff3003c3353', default-features = false }
sp-std = { git = 'https://github.com/paritytech/substrate', rev = '49a4103f4bfef55be20a5c6d26e18ff3003c3353', default-features = false }
sp-runtime = { git = 'https://github.com/paritytech/substrate', rev = '49a4103f4bfef55be20a5c6d26e18ff3003c3353', default-features = false }
sp-io = { git = 'https://github.com/paritytech/substrate', rev = '49a4103f4bfef55be20a5c6d26e18ff3003c3353', default-features = false }

online-profile = { path = '../online-profile', default-features = false }
generic-func = { path = '../generic-func', default-features = false }
dbc-price-ocw = { path = '../dbc-price-ocw', default-features = false }

[dev-dependencies]
once_cell = '1'
hex = '0.4'

pallet-balances = { git = 'https://github.com/paritytech/substrate', rev = '49a4103f4bfef55be20a5c6d26e18ff3003c3353' }
pallet-treasury = { git = 'https://github.com/paritytech/substrate', rev = '49a4103f4bfef55be20a5c6d26e18ff3003c3353' }
sp-core = { git = 'https://github.com/paritytech/substrate', rev = '49a4103f4bfef55be20a5c6d26e18ff3003c3353' }
pallet-randomness-collective-flip = { git = 'https://github.com/paritytech/substrate', rev = '49a4103f4bfef55be20a5c6d26e18ff3003c3353' }
sp-keyring = { git = 'https://github.com/paritytech/substrate', rev = '49a4103f4bfef55be20a5c6d26e18ff3003c3353' }
pallet-collective = { git = 'https://github.com/paritytech/substrate', rev = '49a4103f4bfef55be20a5c6d26e18ff3003c3353' }
pallet-timestamp = { git = 'https://github.com/paritytech/substrate', rev = '49a4103f4bfef55be20a5c6d26e18ff3003c3353' }

committee = { path = '../committee' }
online-committee = { path = '../online-committee' }

[features]
default = ["std"]
std = [
  "codec/std",
  "dbc-price-ocw/std",
  "frame-support/std",
  "frame-system/std",
  "online-profile/std",
  "generic-func/std",
  "serde",
  "sp-io/std",
  "sp-runtime/std",
  "sp-std/std",
]
