name: release

on:
  push:
    branches: [master]

jobs:
  release:
    runs-on: ubuntu-18.04

    steps:
      - name: Add wasm toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly-2022-01-01
          override: true
          target: wasm32-unknown-unknown

      - name: 'Checkout codes'
        uses: actions/checkout@v1

      - name: Compile
        run: cargo build --release

      - name: Create archive
        run: tar czf dbc-daily-release.tar.gz --directory=target/release/ dbc-chain

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          draft: true
          tag_name: daily.release
          files: dbc-daily-release.tar.gz
