name: release

on:
  push:
    branches: [master]

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Add wasm toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly-2022-01-01
          override: true
          target: wasm32-unknown-unknown

      - name: "Checkout codes"
        uses: actions/checkout@v1

      - uses: Swatinem/rust-cache@v2
        with:
          cache-on-failure: "true"

      - name: Compile
        run: cargo build --release

      - name: Create archive
        run: tar czf dbc-daily-release.tar.gz target/release/dbc-chain target/release/wbuild/node-runtime/node_runtime.compact.wasm

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          draft: true
          tag_name: daily.release
          files: dbc-daily-release.tar.gz
