# This is a basic workflow to help you get started with Actions
name: testcase

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [master]
  pull_request:
    branches: [master]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Add wasm toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          target: wasm32-unknown-unknown

      - uses: actions/checkout@v2

      - uses: Swatinem/rust-cache@v2
        with:
          cache-on-failure: "true"

      - name: Run parse price url tests
        run: cargo test -p dbc-price-ocw

      - name: Run machine online tests
        run: cargo test -p online-committee

      - name: Run rent machine tests
        run: cargo test -p rent-machine

      - name: Run maintain machine tests
        run: cargo test -p maintain-committee

      - name: Run committee tests
        run: cargo test -p committee
