[package]
authors = ["bobo <dongkaige@gmail.com>"]
edition = "2018"
name = "committee-rpc"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
codec = { package = "parity-scale-codec", version = "2.0.0", features = [
    "derive",
] }
jsonrpc-core = "15.0"
jsonrpc-core-client = "15.0"
jsonrpc-derive = "15.0"
committee = { version = "0.1.0", path = "../../committee" }
committee-runtime-api = { version = "0.1.0", path = "./runtime-api" }

sp-runtime = { git = 'https://github.com/paritytech/substrate', tag = 'v3.0.0' }
sp-api = { git = 'https://github.com/paritytech/substrate', tag = 'v3.0.0' }
sp-blockchain = { git = 'https://github.com/paritytech/substrate', tag = 'v3.0.0' }
sp-rpc = { git = 'https://github.com/paritytech/substrate', tag = 'v3.0.0' }
